"""Schemas for OpenClaw integration token and ingestion APIs."""

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import Field, model_validator

from app.db.models.integration_token import DEFAULT_OPENCLAW_SCOPES
from app.schemas.base import BaseSchema


class OpenClawTokenCreateRequest(BaseSchema):
    """Request body for creating an OpenClaw token."""

    name: str = Field(..., min_length=1, max_length=255)
    scopes: list[str] = Field(default_factory=lambda: list(DEFAULT_OPENCLAW_SCOPES), min_length=1)
    expires_at: datetime | None = None


class OpenClawTokenRead(BaseSchema):
    """Token metadata returned by integration token APIs."""

    id: UUID
    name: str
    scopes: list[str]
    is_active: bool
    created_at: datetime
    updated_at: datetime | None = None
    last_used_at: datetime | None = None
    expires_at: datetime | None = None


class OpenClawTokenCreateResponse(BaseSchema):
    """Response when a token is created."""

    token: str = Field(description="Plaintext token shown once. Store it securely.")
    token_info: OpenClawTokenRead


class OpenClawTokenListResponse(BaseSchema):
    """List response for OpenClaw tokens."""

    items: list[OpenClawTokenRead]
    total: int


class OpenClawJobInput(BaseSchema):
    """Single job payload sent from OpenClaw."""

    title: str = Field(..., min_length=1, max_length=500)
    company: str = Field(..., min_length=1, max_length=255)
    job_url: str = Field(..., min_length=1, max_length=2048)
    location: str | None = Field(default=None, max_length=255)
    description: str | None = None
    salary_range: str | None = Field(default=None, max_length=100)
    date_posted: datetime | None = None
    source: str | None = Field(default=None, max_length=50)
    is_remote: bool | None = None
    job_type: str | None = Field(default=None, max_length=50)
    company_url: str | None = Field(default=None, max_length=2048)
    relevance_score: float | None = Field(
        default=None,
        ge=0.0,
        le=10.0,
        description="Optional external relevance score generated by OpenClaw.",
    )
    reasoning: str | None = Field(
        default=None,
        max_length=4000,
        description="Optional external reasoning text generated by OpenClaw.",
    )
    application_type: Literal["easy_apply", "ats", "direct", "email", "unknown"] | None = None
    application_url: str | None = Field(default=None, max_length=2048)
    requires_cover_letter: bool | None = None
    requires_resume: bool | None = None
    detected_fields: dict[str, Any] | None = None
    screening_questions: list[dict[str, Any]] | None = None
    analyzed_at: datetime | None = None

    @property
    def has_application_analysis(self) -> bool:
        """Return whether this payload contains application-page analysis fields."""
        return any(
            value is not None
            for value in (
                self.application_type,
                self.application_url,
                self.requires_cover_letter,
                self.requires_resume,
                self.detected_fields,
                self.screening_questions,
            )
        )

    @model_validator(mode="after")
    def validate_analysis_fields(self):
        """Require a score when external reasoning is provided."""
        if self.reasoning is not None and self.relevance_score is None:
            raise ValueError("relevance_score is required when reasoning is provided")
        if self.analyzed_at is not None and not self.has_application_analysis:
            raise ValueError(
                "Application analysis fields are required when analyzed_at is provided"
            )
        return self


class OpenClawJobsIngestRequest(BaseSchema):
    """Request for bulk ingesting jobs discovered by OpenClaw."""

    jobs: list[OpenClawJobInput] = Field(..., min_length=1)
    profile_id: UUID | None = Field(
        default=None, description="Optional profile for AI scoring context"
    )
    analyze_with_profile: bool = Field(
        default=True,
        description="If true, use profile resume text and preferences for AI scoring when available.",
    )
    save_all: bool = Field(
        default=True,
        description="If true, save jobs even when they do not meet min_score.",
    )
    min_score: float | None = Field(
        default=None,
        ge=0.0,
        le=10.0,
        description="Optional score threshold override when analysis is enabled.",
    )
    search_terms: str | None = Field(default=None, max_length=500)
    qa_with_internal_analysis: bool = Field(
        default=False,
        description=(
            "If true, run internal profile-based analysis for QA comparison while still storing "
            "external scores/reasoning."
        ),
    )

    @model_validator(mode="after")
    def validate_qa_options(self):
        """QA analysis requires profile analysis context to be enabled."""
        if self.qa_with_internal_analysis and not self.analyze_with_profile:
            raise ValueError("qa_with_internal_analysis requires analyze_with_profile=true")
        return self


class OpenClawJobsIngestResponse(BaseSchema):
    """Result summary for OpenClaw job ingestion."""

    jobs_received: int
    jobs_analyzed: int
    jobs_saved: int
    duplicates_skipped: int
    high_scoring: int
    analysis_enabled: bool
    external_analysis_used: bool
    qa_with_internal_analysis: bool = False
    qa_jobs_checked: int = 0
    qa_large_score_drift: int = 0
    profile_id: UUID | None = None
    profile_name: str | None = None
    token_id: UUID
    token_name: str


class OpenClawJobAnalyzeRequest(BaseSchema):
    """Application analysis payload sent by OpenClaw for an existing job."""

    description: str | None = None
    application_type: Literal["easy_apply", "ats", "direct", "email", "unknown"] | None = None
    application_url: str | None = Field(default=None, max_length=2048)
    requires_cover_letter: bool | None = None
    requires_resume: bool | None = None
    detected_fields: dict[str, Any] | None = None
    screening_questions: list[dict[str, Any]] | None = None
    analyzed_at: datetime | None = None

    @model_validator(mode="after")
    def validate_has_analysis_fields(self):
        """Require at least one real application-analysis field."""
        has_application_analysis = any(
            value is not None
            for value in (
                self.application_type,
                self.application_url,
                self.requires_cover_letter,
                self.requires_resume,
                self.detected_fields,
                self.screening_questions,
            )
        )
        if not has_application_analysis:
            raise ValueError("At least one application analysis field is required")
        return self


class OpenClawPrepBatchRequest(BaseSchema):
    """Request to synchronously prep analyzed jobs from OpenClaw."""

    job_ids: list[UUID] | None = None
    max_jobs: int = Field(default=20, ge=1, le=50)
    tone: Literal["professional", "conversational", "enthusiastic"] = "professional"


class OpenClawApplySuccessRequest(BaseSchema):
    """Payload to record a successful application submitted by OpenClaw."""

    applied_at: datetime | None = None
    application_method: str | None = Field(default="openclaw", max_length=50)
    confirmation_code: str | None = Field(default=None, max_length=255)
    notes: str | None = None
